name: CI and documentation

on:
  push:
    branches-ignore:
      - main
  workflow_dispatch:

jobs:

  checks:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4.2.2

    - name: Install Python versions
      uses: actions/setup-python@v5.4.0
      with:
        python-version: |
            3.10
            3.11
            3.12

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4.3
      with:
        cache: true
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: pdm install --no-default -dG maintenance -dG checks

    - name: Check code quality
      run: pdm checks quality

    - name: Check type annotations
      run: pdm checks types

    - name: Check vulnerabilities in dependencies
      run: pdm checks dependencies

  tests:

    strategy:
      matrix:
        os:
        - ubuntu-latest
        - macos-latest
        - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install Python versions
      uses: actions/setup-python@v5.4.0
      with:
        python-version: |
            3.10
            3.11
            3.12

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4.3
      with:
        cache: true
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: pdm install -dG maintenance -dG tests

    - name: Run the test suite
      run: pdm tests

  doc:

    runs-on: ubuntu-latest

    strategy:
      matrix:
          python-version: ['3.10', '3.11', '3.12']

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up PDM
      uses: pdm-project/setup-pdm@v4.3
      with:
        cache: true
        cache-dependency-path: pyproject.toml

    - name: Install dependencies
      run: pdm install -dG maintenance -dG docs

    - name: Build documentation with Python ${{ matrix.python-version }}
      run: pdm docs build
